name: Go Linter
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  golangci:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
          only-new-issues: true
